### PR TITLE
Implemented VesselType condition

### PR DESCRIPTION
**Pull request by supervoltage**
I have added the VesselType condition to the playlists and made it accessible to user modification.

The VesselType is based on the vessel's current icon, as selected in the Rename Vessel window from the map view in KSP or by clicking on "Configure Vessel Naming" on the command pod of the vessel.

I have noted that it will get confused if there is more than one command pod on the vessel and won't switch playlists, but if the vessel is renamed from the map view it will work accordingly.

### CODE REVIEW

**Comment by linuxgurugamer** [comment]
when checking for the command pod, try adding something which remembers which vessel it's on it might be helpful

**Comment by supervoltage** [comment]
Thanks for the reply! I did a little more digging and it turns out it seems there was an error on my part. Turns out that the buttons "Configure Vessel Naming" and "Rename Vessel" do **not** achieve the same purpose.

Upon re-testing with a craft that has multiple command pods, I can confirm that the existing code successfully updates the playlist upon renaming the craft, either from the map view or from the vessel itself. Success!

**Comment by linuxgurugamer** [comment]
Could you do a little writeup describing the new functionality?

**Comment by supervoltage** [comment]
Certainly, you may find a description of what it does below.

A new UI element called "Vessel Type" is added to the Playlist editor, just underneath the "Vessel State". Upon expanding this new UI element, a list of various vessel types is displayed to the user, including but not limited to: Ship, Rover, Plane, Probe, Relay etc. This allows users to create, for example, atmospheric playlists that are for either aircraft or rocket use, among a myriad of other possibilities when used in combination with other playlist criteria.

A hook into the `Vessel.onVesselRename()` method allows the playlist to immediately change when the vessel type changes in-game, say if the vessel is renamed via the "Rename Vessel" function, when the vessel splits into two distinct vessel types (for example, undocking a rover), or when switching to another nearby vessel using the square bracket [] keys.

This new playlist criteria saves accordingly to existing playlist.cfg files, meaning users won't have to re-create their playlists either.

I hope the above description is suitable. Any other questions, feel free to ask!

**Pull request merged**
